import React from "react"
import { Footer } from "@/components/footer/Footer"

export const metadata = {
  title: 'Employee participation',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Footer/>
    </html>
  )
}
